version: '3.9'

services:
  ledeoya-admin:
    build:
      context: .
      dockerfile: Dockerfile
    image: ledeoya-app:latest
    ports:
      - "4321:4321"
    env_file:
      - .env
    environment:
      NODE_ENV: production
      APP_SECRET: ${APP_SECRET}
      DATABASE_URL: ${DATABASE_URL}
    restart: unless-stopped
