version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ledeoya-app:latest
    ports:
      - "4321:4321"
    env_file:
      - .env
    environment:
      NODE_ENV: production
    restart: unless-stopped
